### ISSUE TITLE
Upgrade to 4.1.0 returns missing module

### ISSUE THREAD

**Issue by vmario89** [Lissy93/dashy#2141]
### Environment

Self-Hosted - self-compiled
### System

Ubuntu LTS 26, Node.js v20.19.5

### Version

4.1.0

### Describe the problem

Hi, since upgrade from 4.0.0 to 4.1.0 the compilation succeeds, but dashy does not start:

```
Mai 16 22:53:01 REDACTED yarn[3185]: node:internal/modules/cjs/loader:1210
Mai 16 22:53:01 REDACTED yarn[3185]:   throw err;
Mai 16 22:53:01 REDACTED yarn[3185]:   ^
Mai 16 22:53:01 REDACTED yarn[3185]: Error: Cannot find module 'jose'
Mai 16 22:53:01 REDACTED yarn[3185]: Require stack:
Mai 16 22:53:01 REDACTED yarn[3185]: - /opt/dashy/services/auth-oidc.js
Mai 16 22:53:01 REDACTED yarn[3185]: - /opt/dashy/services/app.js
Mai 16 22:53:01 REDACTED yarn[3185]: - /opt/dashy/server.js
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module._load (node:internal/modules/cjs/loader:1038:27)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module.require (node:internal/modules/cjs/loader:1289:19)
Mai 16 22:53:01 REDACTED yarn[3185]:     at require (node:internal/modules/helpers:182:18)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Object.<anonymous> (/opt/dashy/services/auth-oidc.js:15:43)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module._compile (node:internal/modules/cjs/loader:1521:14)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module.load (node:internal/modules/cjs/loader:1266:32)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module._load (node:internal/modules/cjs/loader:1091:12)
Mai 16 22:53:01 REDACTED yarn[3185]:     at Module.require (node:internal/modules/cjs/loader:1289:19) {
Mai 16 22:53:01 REDACTED yarn[3185]:   code: 'MODULE_NOT_FOUND',
Mai 16 22:53:01 REDACTED yarn[3185]:   requireStack: [
Mai 16 22:53:01 REDACTED yarn[3185]:     '/opt/dashy/services/auth-oidc.js',
Mai 16 22:53:01 REDACTED yarn[3185]:     '/opt/dashy/services/app.js',
Mai 16 22:53:01 REDACTED yarn[3185]:     '/opt/dashy/server.js'
Mai 16 22:53:01 REDACTED yarn[3185]:   ]
Mai 16 22:53:01 REDACTED yarn[3185]: }
Mai 16 22:53:01 REDACTED yarn[3185]: Node.js v20.19.5
Mai 16 22:53:01 REDACTED yarn[3155]: error Command failed with exit code 1.
```
```
npm install jose
```
```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: dashy@4.1.0
npm warn Found: vue@3.5.32
npm warn node_modules/vue
npm warn   peer vue@">=3.2.13" from vite-svg-loader@5.1.1
npm warn   node_modules/vite-svg-loader
npm warn     dev vite-svg-loader@"^5.1.0" from the root project
npm warn   11 more (vue-i18n, vue-router, vue-select, vuex, @jsonforms/vue, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer vue@"3.5.32" from @vue/server-renderer@3.5.32
npm warn node_modules/@vue/server-renderer
npm warn   @vue/server-renderer@"3.5.32" from vue@3.5.32
npm warn   node_modules/vue
npm warn   1 more (@vue/test-utils)

added 4 packages, removed 17 packages, changed 77 packages, and audited 668 packages in 1m

176 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

the vuln can be fixed by `npm audit fix` - sadly i exexuted the this before `npm audit` so i did not see the reason.

after installing, it works again

### Please tick the boxes

- [x] You have explained the issue clearly, and included all relevant info
- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [x] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [x] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by lissy93** [comment]
Hey @vmario89 
That's weird... lemme take a look 👀

**Comment by lissy93** [comment]
Ah, I think I see the issue...
Some old dependencies + lockfile you had left over, plus you're using `Node.js v20.19.5` and `npm`

You shouldn't need to modify the lockfile, or anything. And there's no vulnerable packages right now :)
There's just been a lot of dependency updates in the latest version, and you've not yet installed them. Quickest solution is just `rm -rf node_modules package-lock.json && npm i`
Also, when you can, consider updating your Node.js version, and consider switching to yarn. 

These steps will solve it (you probably won't need all of them)...
- Remove the node modules and package-lock.json: `rm -rf node_modules package-lock.json`
- Switch to more recent Node version (if you can): `nvm install v24.11.0 && nvm use v24.11.0`
- Enable yarn (if not already done so): `corepack enable`
- Re-install dependencies: `yarn install --frozen-lockfile`
- Then, re-build: `yarn build`
- And start: `yarn start`

**Comment by vmario89** [comment]
yeah; i got it before you answered too, but many thanks for your reply. you have a lot more stable build steps than my DIY script ;D but at least i was able to upgrade last 10 versions ^^ i will fix my documentation and update script as well to less bother you with supporting of issues like mine
